apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-pg-db
  labels:
    app: todo-pg-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-pg-db
  template:
    metadata:
      labels:
        app: todo-pg-db
    spec:
      containers:
        - name: todo-pg-db
          image: todo-db
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "tododb"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: todo-pg-db
  labels:
    app: todo-pg-db
spec:
  selector:
    app: todo-pg-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP